# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - labdotenv

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Create and start virtual environment
        env:
          TEST1: ${{secrets.TEST1}}
          TEST_2: ${{secrets.TEST_2}}
        run: |
          python -m venv venv
          source venv/bin/activate
          echo this is a secret ${{secrets.TEST_2}}
          echo this is a secret too ${{secrets.TEST_2}}

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    
    env:
      TEST_2: ${{secrets.TEST_2}}
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        env: 
          TEST_2: ${{secrets.TEST_2}}
        run: | 
          unzip release.zip
          echo this is a secret too ${{secrets.TEST_2}}


      - name: "Deploy to Azure Web App"
        env: 
          TEST_2: ${{secrets.TEST_2}}
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "labdotenv"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3331A6632FB84D8C95EF1E8663CD7DC5 }}
          
